version: "3"


services:

  adservice:

    image: adservice

    

    ports:

      - "9555:9555"




    environment:

      PORT: "9555"




  redis:

    image: redis

   

    ports:

      - "6379:6379"




   




  cartservice:

    image: cartservice

   
    ports:

      - "7070:7070"




    environment:

        REDIS_ADDR: "redis:6379"




  frontend:

    image: frontend

    

    ports:

      - "8080:8080"




    environment:




        PORT: "8080"

        PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"

        CURRENCY_SERVICE_ADDR: "currencyservice:7000"

        CART_SERVICE_ADDR: "cartservice:7070"

        RECOMMENDATION_SERVICE_ADDR: "recommendationservice:8081"

        SHIPPING_SERVICE_ADDR: "shippingservice:50051"

        CHECKOUT_SERVICE_ADDR: "checkoutservice:5050"

        AD_SERVICE_ADDR: "adservice:9555"




  currencyservice:

    image: currencyservice

   

    ports:

      - "7000:7000"




    environment:

        PORT: "7000"

        DISABLE_PROFILER: "1"




  checkoutservice:

    image: checkoutservice

    

    ports:

      - "5050:5050"




    environment:

          name: PORT

          PORT: "5050"

          PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"

          SHIPPING_SERVICE_ADDR: "shippingservice:50051"

          PAYMENT_SERVICE_ADDR: "paymentservice:50051"

          EMAIL_SERVICE_ADDR: "emailservice:5000"

          CURRENCY_SERVICE_ADDR: "currencyservice:7000"

          CART_SERVICE_ADDR: "cartservice:7070"




  emailservice:

    image: emailservice

   

    ports:

      - "8081:8080"




    environment:

          PORT: "8080"

          DISABLE_PROFILER: "1"




  loadgenerator:

    image: loadgenerator

    

    ports:

      - "80:80"




    environment:

          FRONTEND_ADDR: "frontend:80"

          USERS: "10"




  paymentservice:

    image: paymentservice

   

    ports:

      - "50051:50051"




    environment:

          PORT: "50051"

          DISABLE_PROFILER: "1"




  productcatalogservice:

    image: productcatalogservice

   

    ports:

      - "3550:3550"




    environment:

          PORT: "3550"

          DISABLE_PROFILER: "1"




  recommendationservice:

    image: recommendationservice

    

    ports:

      - "8082:8080"




    environment:

          PORT: "8080"

          PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"

          DISABLE_PROFILER: "1"




  shippingservice:

    image: shippingservice

    

    ports:

      - "50052:50051"




    environment:

          PORT: "50051"

          DISABLE_PROFILER: "1"
